### ISSUE TITLE
How to build this module and use in Qt?

### ISSUE THREAD

**Issue by shujaatak** [pauldotknopf/qt-module-example#1]
I want to learn making custom modules in Qt and while searching on internet I found your repository. I hope you may help me in this regard.
I have developed few widgets and I can use them directly in my projects and I can use the libraries version too but I want to make a module **mywidgets** and use it like Qt += mywidgets, is it possible? if yes then how can I make one?
As I am inexperienced in this regard so I even do not know how to build your qt-module-example in QtCreator! Can you please mention the steps how to build your sample qt-module-example and use/test it?
I would be much thankful for any help!

**Comment by pauldotknopf** [comment]
Start with this repro as a template, and replace all files/references to "mod" with "mywidgets".

**Comment by shujaatak** [comment]
I am going to try this and let you update about the status.

**Comment by shujaatak** [comment]
@pauldotknopf I tried to build `qt-module-example` but it only generates the following files and folders I don't know what to do next :(

![capture](https://user-images.githubusercontent.com/14161646/47629081-eb898d00-db5a-11e8-891a-753a7fdbb9bd.PNG)

I am using QtCreator for building the code. Windows 10.

**Comment by shujaatak** [comment]
I finally succeeded in building a working module! Thank you!

**Comment by momolegamer** [comment]
Can You explain to me the solution @shujaatak. I have the same problem, the compilation was good, now i have the same building and the next ?
